# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift' do
  pod 'Geniee-iOS-SDK'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Geniee-Google-Mediation-Adapter'
  pod 'Geniee-Mediation-AppLovin-Adapter'
  pod 'Geniee-Mediation-GoogleAdManager-Adapter'
  pod 'Geniee-Mediation-Pangle-Adapter'
  pod 'Geniee-Mediation-UnityAds-Adapter'
  pod 'Geniee-Mediation-Maio-Adapter'
  pod 'Geniee-Mediation-Line-Adapter'

end
