# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNAdFullscreenInterstitialSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for GNAdFullscreenInterstitialSample
  pod 'Geniee-iOS-SDK', :git => 'https://github.com/geniee-ssp/Geniee-iOS-SDK.git', :branch => 'feature/fullscreen_mediation'
  pod 'AppLovinSDK','~> 5.1.1'
  pod 'MaioSDK', '~> 1.4.0'
  pod 'NendSDK_iOS', '~> 5.0.2'
  pod 'ZucksAdNetworkSDK', '~> 4.7.8'

end
