# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenieeFullscreenInterstitialSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenieeFullscreenInterstitialSample
  
  pod 'Geniee-iOS-SDK'
  pod 'AppLovinSDK'
  pod 'UnityAds'
  pod 'Ads-Global'
  pod 'VungleAds'
  pod 'MaioSDK'
  pod 'Google-Mobile-Ads-SDK'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end

  target 'GenieeFullscreenInterstitialSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenieeFullscreenInterstitialSampleUITests' do
    # Pods for testing
  end

end
