# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNAdSampleNativeAd' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Geniee-iOS-SDK','~> 7.0.5'
end
