# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNAdRewardVideoSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GNAdRewardVideoSample
  pod 'Geniee-iOS-SDK', :git => 'https://github.com/geniee-ssp/Geniee-iOS-SDK.git', :branch => 'master'
  pod 'AdColony', '~> 3.3.4'
  pod 'AppLovinSDK','~> 5.0.1'
  pod 'MaioSDK', '~> 1.3.0'
  pod 'NendSDK_iOS', '~> 4.0.6'
  pod 'TapjoySDK', '~> 11.12.2'
  pod 'UnityAds', '~> 2.2.1'
  pod 'VungleSDK-iOS', '~> 6.2.0'

end
