# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNCAdSampleBanner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
# when local test path

 pod 'Geniee-iOS-SDK', :git => 'https://github.com/geniee-ssp/Geniee-iOS-SDK.git', :branch => 'develop'

end
