# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNAdRewardVideoSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'Geniee-iOS-SDK', :git => 'https://github.com/geniee-ssp/Geniee-iOS-SDK.git', :branch => 'develop'
  pod 'AdColony', '~> 3.3.4'
  pod 'AppLovinSDK','~> 5.0.1'
  pod 'MaioSDK', '~> 1.3.0'
  pod 'NendSDK_iOS', '~> 4.0.6'
  pod 'TapjoySDK', '~> 11.12.2'
  pod 'UnityAds', '~> 2.2.1'
  pod 'VungleSDK-iOS', '~> 6.2.0'
end
