source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'GNAdGoogleRewardMediationAdapterSample' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'Geniee-iOS-SDK'
  pod 'Geniee-Google-Mediation-Adapter'
  pod 'AdColony', '~> 3.3.5'
  pod 'AppLovinSDK','~> 6.9.4'
  pod 'MaioSDK', '~> 1.4.0'
  pod 'NendSDK_iOS', '~> 5.3.0'
  pod 'TapjoySDK', '~> 12.3.4'
  pod 'UnityAds', '~> 3.3.0'
  pod 'VungleSDK-iOS', '~> 6.4.5'
  pod 'Bytedance-UnionAD', '~> 2.4.6.7'

end
