source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'GNAdGoogleRewardMediationAdapterSample' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'Geniee-iOS-SDK'
  pod 'AdColony', '~> 3.3.5'
  pod 'AppLovinSDK','~> 5.1.1'
  pod 'MaioSDK', '~> 1.4.0'
  pod 'NendSDK_iOS', '~> 5.0.2'
  pod 'TapjoySDK', '~> 12.0.0'
  pod 'UnityAds', '~> 2.3.0'
  pod 'VungleSDK-iOS', '~> 6.2.0'

end
