# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'GNAdGoogleBannerAdapterSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GNAdGoogleBannerAdapterSample
  pod 'Google-Mobile-Ads-SDK'
  pod 'Geniee-iOS-SDK'
  pod 'Geniee-Google-Mediation-Adapter'

end
